dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - python setup.py install
  - pip install pytest-cov
script:
  - pytest --cov=pyas2lib --cov-config .coveragerc
after_success:
  - pip install codecov
  - codecov